import sys
import subprocess
import os

def main():

    # dir
    sim_dir = r'sim/'
    rtl_dir = r'rtl/'
    tb_file = r'tb/' + sys.argv[1] + r'_tb.v'
    rtl_files = os.listdir(rtl_dir)
    
    # compile rtl by iverilog
    iverilog_cmd = ['iverilog'] # iverilog
    iverilog_cmd += ['-o', sim_dir + r'dumpfile/out.vvp'] # compile result
    iverilog_cmd += ['-D', r'OUTPUT="signature.output"'] # simulation output file
    iverilog_cmd.append(tb_file) # testbench
    for file in rtl_files:
        iverilog_cmd.append(rtl_dir + file)
    process = subprocess.Popen(iverilog_cmd)
    process.wait(timeout=5)

    # executes the default compiled form generated by Icarus Verilog
    vvp_cmd = [r'vvp']
    vvp_cmd.append(sim_dir + r'dumpfile/out.vvp')
    process = subprocess.Popen(vvp_cmd)
    try:
        process.wait(timeout=20)
    except subprocess.TimeoutExpired:
        print('!!!Fail, vvp exec timeout!!!')

    # open "wave.vcd" to inspect waves 
    cmd = r'gtkwave ' + sim_dir + r'dumpfile/wave.vcd'
    f = os.popen(cmd)
    f.close()

if __name__ == '__main__':
    sys.exit(main())